name: "NPM_TOKEN"

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: node
        uses: actions/setup-node@v3
      - name: 🚀 release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm whoami
          echo ${#NPM_TOKEN}
